import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import Header from "@/components/Header";
import { UserProvider } from "@/context/UserContext";
import WalletDrawer from "@/components/WalletDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solana wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0a0a] text-white max-w-md mx-auto min-h-screen max-h-screen relative overflow-hidden` }
      >
        <UserProvider>
          <Header />
          <WalletDrawer />
          {children}
        </UserProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
